#!/usr/bin/env python3
"""2h drip: append a deterministic batch of generated PC models to the depository.
Mirrors the combinatorial space in js/gen.js (same seed scheme) so the march to
1,000,000 stays contiguous. Silent except milestones; never invents history."""
import json, os, random, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA = os.path.join(ROOT, "data")
DRIP = os.path.join(DATA, "drip")
os.makedirs(DRIP, exist_ok=True)

ARCH = ["von Neumann", "Harvard", "Dataflow", "Neuromorphic", "Systolic Array",
        "Quantum-Classical Hybrid", "Analog-Digital", "Photonic Mesh"]
MATS = ["Silicon", "Germanium", "GaAs", "Graphene", "Diamond", "SiC", "Photonic SiN", "Memristor"]
WIDTHS = [4, 8, 16, 32, 64, 128]
SCALES = ["Board", "Rack", "Cluster", "Wafer-Scale", "Chiplet"]
BATCH = int(sys.argv[1]) if len(sys.argv) > 1 else 400

count_path = os.path.join(DATA, "count.json")
count = {"seed": 0, "generated": 0}
if os.path.exists(count_path):
    count = json.load(open(count_path))
try:
    seed_recs = json.load(open(os.path.join(DATA, "systems.json")))
    count["seed"] = len(seed_recs)
except Exception:
    pass

start = count["generated"]
recs = []
for k in range(BATCH):
    i = start + k
    rng = random.Random(10_000_000 + i)  # generated space sits above the on-demand space
    arch = rng.choice(ARCH); mat = rng.choice(MATS)
    w = rng.choice(WIDTHS); sc = rng.choice(SCALES)
    name = f"Signature {mat} {arch} {w}-bit {sc} Unit {i+1:06d}"
    recs.append({
        "id": f"pcm-gen-{i+1:06d}",
        "name": name,
        "cat": "predicted",
        "era": "Generated",
        "tag": "Combinatorial model",
        "desc": f"A deterministically generated possible model: {w}-bit {arch} architecture on a {mat} substrate at {sc} scale.",
        "history": "Generated by the depository's combinatorial engine; a possible model, not a historical record.",
        "kind": "predicted",
        "patent": None,
        "demo": "gates",
        "sig": {"name": name,
                "blurb": "A Signature-charted possible model from the million-march combinatorial space.",
                "demo": "gates"},
    })

chunk_n = start // BATCH
chunk_path = os.path.join(DRIP, f"chunk-{chunk_n:04d}.jsonl")
with open(chunk_path, "w") as f:
    for r in recs:
        f.write(json.dumps(r) + "\n")

count["generated"] = start + BATCH
json.dump(count, open(count_path, "w"))

# last-updated stamp (read by the page header, visually separate from the counters)
stamp = {
    "updated": __import__("datetime").date.today().isoformat(),
    "recorded": count["seed"] + count["generated"],
    "seed": count["seed"],
    "generated": count["generated"],
    "source": "PC depository drip (code/drip/append_models.py)",
}
json.dump(stamp, open(os.path.join(DATA, "last-updated.json"), "w"), indent=1)
print(f"DRIP: +{BATCH} generated, seed={count['seed']}, generated={count['generated']}")

# --- static crawlable counts: refresh the <!-- STATIC-COUNTS-... --> block in
# index.html so curl/raw-HTML readers see current numbers (with as-of date and
# the recorded/Signature/generated/simulated distinctions). Additive only.
try:
    from collections import Counter
    seeds = json.load(open(os.path.join(DATA, "systems.json")))
    kinds = Counter(r.get("kind") for r in seeds)
    kind_line = (f"{kinds.get('historical', 0)} historical records, "
                 f"{kinds.get('signature', 0)} Signature-original designs, "
                 f"{kinds.get('predicted', 0)} predicted concepts")
    sig_n = sum(1 for r in seeds if r.get("sig")) + count["generated"]
    rec_n = count["seed"] + count["generated"]
    html_path = os.path.join(ROOT, "index.html")
    html = open(html_path).read()
    block = (
        '<div class="hud" id="crawl-counts">\n'
        '<h2>THE COUNT — ON FILE VS. GENERATABLE</h2>\n'
        f'<p class="kv">Completed systems on file: <b>{rec_n:,}</b> '
        f'<span class="hist">(as of {stamp["updated"]})</span></p>\n'
        '<ul style="font-size:13px;color:#d7e9f7;margin:4px 0;padding-left:18px">\n'
        f'<li><b>RECORDED</b> — {len(seeds)} seed records: {kind_line}.</li>\n'
        f'<li><b>SIGNATURE</b> — {sig_n:,} Signature systems on file: every record carries a Signature-made version.</li>\n'
        f'<li><b>GENERATED</b> — {count["generated"]:,} deterministically generated models (drip chunks), each reproducible from its seed.</li>\n'
        '<li><b>SIMULATED</b> — every system on file ships a working in-browser simulator; sample any file right here.</li>\n'
        '</ul>\n'
        '<p class="kv">Generatable model space: <b>1,000,000</b> possible models '
        '(<span class="hist">JAH-PC-00000001</span> through <span class="hist">JAH-PC-01000000</span>) '
        '— computed on demand from components × architectures × materials × scales. Nothing stored, nothing slow.</p>\n'
        '<p class="kv hist">Static snapshot for crawlers; live counters above update in your browser. Refreshed by the depository drip every 2 hours.</p>\n'
        '</div>'
    )
    start_m, end_m = "<!-- STATIC-COUNTS-START -->", "<!-- STATIC-COUNTS-END -->"
    if start_m in html and end_m in html:
        pre = html.split(start_m)[0] + start_m + "\n"
        post = "\n" + end_m + html.split(end_m)[1]
        open(html_path, "w").write(pre + block + post)
        print(f"STATIC-COUNTS: index.html refreshed (recorded={rec_n}, as of {stamp['updated']})")
    else:
        print("STATIC-COUNTS: markers not found in index.html — skipped")
except Exception as e:  # noqa: BLE001 - drip must never die on the static block
    print(f"STATIC-COUNTS: skipped ({e})")

# --- sitemap: regenerate so new generated models appear as crawlable URLs
try:
    import subprocess
    subprocess.run([sys.executable, os.path.join(ROOT, "code", "gen_sitemap.py")],
                   check=True, capture_output=True, text=True)
    print("SITEMAP: regenerated")
except Exception as e:  # noqa: BLE001
    print(f"SITEMAP: skipped ({e})")
