#!/usr/bin/env python3
"""2h drip: append a deterministic batch of generated PC models to the depository.
Mirrors the combinatorial space in js/gen.js (same seed scheme) so the march to
1,000,000 stays contiguous. Silent except milestones; never invents history."""
import json, os, random, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA = os.path.join(ROOT, "data")
DRIP = os.path.join(DATA, "drip")
os.makedirs(DRIP, exist_ok=True)

ARCH = ["von Neumann", "Harvard", "Dataflow", "Neuromorphic", "Systolic Array",
        "Quantum-Classical Hybrid", "Analog-Digital", "Photonic Mesh"]
MATS = ["Silicon", "Germanium", "GaAs", "Graphene", "Diamond", "SiC", "Photonic SiN", "Memristor"]
WIDTHS = [4, 8, 16, 32, 64, 128]
SCALES = ["Board", "Rack", "Cluster", "Wafer-Scale", "Chiplet"]
BATCH = int(sys.argv[1]) if len(sys.argv) > 1 else 400

count_path = os.path.join(DATA, "count.json")
count = {"seed": 0, "generated": 0}
if os.path.exists(count_path):
    count = json.load(open(count_path))
try:
    seed_recs = json.load(open(os.path.join(DATA, "systems.json")))
    count["seed"] = len(seed_recs)
except Exception:
    pass

start = count["generated"]
recs = []
for k in range(BATCH):
    i = start + k
    rng = random.Random(10_000_000 + i)  # generated space sits above the on-demand space
    arch = rng.choice(ARCH); mat = rng.choice(MATS)
    w = rng.choice(WIDTHS); sc = rng.choice(SCALES)
    name = f"Signature {mat} {arch} {w}-bit {sc} Unit {i+1:06d}"
    recs.append({
        "id": f"pcm-gen-{i+1:06d}",
        "name": name,
        "cat": "predicted",
        "era": "Generated",
        "tag": "Combinatorial model",
        "desc": f"A deterministically generated possible model: {w}-bit {arch} architecture on a {mat} substrate at {sc} scale.",
        "history": "Generated by the depository's combinatorial engine; a possible model, not a historical record.",
        "kind": "predicted",
        "patent": None,
        "demo": "gates",
        "sig": {"name": name,
                "blurb": "A Signature-charted possible model from the million-march combinatorial space.",
                "demo": "gates"},
    })

chunk_n = start // BATCH
chunk_path = os.path.join(DRIP, f"chunk-{chunk_n:04d}.jsonl")
with open(chunk_path, "w") as f:
    for r in recs:
        f.write(json.dumps(r) + "\n")

count["generated"] = start + BATCH
json.dump(count, open(count_path, "w"))

# last-updated stamp (read by the page header, visually separate from the counters)
stamp = {
    "updated": __import__("datetime").date.today().isoformat(),
    "recorded": count["seed"] + count["generated"],
    "seed": count["seed"],
    "generated": count["generated"],
    "source": "PC depository drip (code/drip/append_models.py)",
}
json.dump(stamp, open(os.path.join(DATA, "last-updated.json"), "w"), indent=1)
print(f"DRIP: +{BATCH} generated, seed={count['seed']}, generated={count['generated']}")
